apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
  labels:
    environment: prod
    managedBy: argocd
    project: eks-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Production cluster applications (ca-west-1)

  sourceRepos:
    - https://github.com/kyenzo/devops_demo.git
    - https://charts.jetstack.io
    - https://strimzi.io/charts/
    - https://provectus.github.io/kafka-ui-charts
    - https://kyverno.github.io/kyverno/
    - https://prometheus-community.github.io/helm-charts
    - https://kubernetes.github.io/ingress-nginx

  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
