# Namespaced Issuer backed by the trust anchor secret.
# cert-manager uses this to sign the identity issuer certificate.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
