replicaCount: 2

image:
  repository: 449873021552.dkr.ecr.ca-west-1.amazonaws.com/apps/web-server
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8086

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

podAnnotations:
  # Datadog autodiscovery annotations
  ad.datadoghq.com/web-server.check_names: '["prometheus"]'
  ad.datadoghq.com/web-server.init_configs: '[{}]'
  ad.datadoghq.com/web-server.instances: '[{"prometheus_url": "http://%%host%%:8086/metrics", "namespace": "web-server", "metrics": ["*"]}]'
  ad.datadoghq.com/web-server.logs: '[{"source": "python", "service": "web-server"}]'

ingress:
  enabled: true
  className: nginx
  path: /api(/|$)(.*)
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"

env:
  PORT: "8086"
  CLUSTER_NAME: "prod"
