apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  namespace: argocd
  labels:
    environment: prod
    managedBy: argocd
    project: eks-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Multi-source: Strimzi Helm chart + values from our Git repo
  sources:
    - repoURL: https://strimzi.io/charts/
      chart: strimzi-kafka-operator
      targetRevision: 0.49.1
      helm:
        valueFiles:
          - $values/helm/kafka/values.yaml

    - repoURL: https://github.com/kyenzo/devops_demo.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
