apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-server
  namespace: argocd
  labels:
    environment: prod
    managedBy: argocd
    project: eks-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/kyenzo/devops_demo.git
    targetRevision: master
    path: helm/web-server

  destination:
    server: https://kubernetes.default.svc
    namespace: web-server

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m

